config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :books
  root 'books#index'

  get '/about', to: 'pages#about'

end

app/models/book.rb
class Book < ActiveRecord::Base
  # sprawdzamy czy jest treść w tym co podaje użytkownik
  validates :title, presence: true, length: { minimum: 3 }
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show] #co się pokaże, gdy nie jest się zalogowanym

  def index
    @books = Book.paginate :page => params[:page], :per_page => 10
  end

  def new 
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
      if @book.save 
        redirect_to @book
      else 
      	render 'new'
      end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
	@book = Book.find(params[:id])
		if @book.update(params[:book].permit(:title, :name, :surname, :subtitle, :isbn, :color, :category, :tags, :lease, :cover))
			redirect_to @book
		else
			render 'edit'
		end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to root_path
  end


  private
    def book_params
    	params.require(:book).permit(:title, :name, :surname, :subtitle, :isbn, :color, :category, :tags, :lease, :cover)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
      
      <!-- powiadomienie flash -->
      <% if @book.errors.any? %>
        <div id="errors">
          <h2><%= pluralize(@book.errors.count, "error") %> prevented this book from saving</h2>
            <ul>
              <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
      <% end %>

      <p>
    	  <%= f.label 'title' %><br>
    	  <%= f.text_field :title %>
      </p>
      <p>
    	  <%= f.label 'subtitle' %><br>
    	  <%= f.text_field :subtitle %>
      </p>
      <p>
    	  <%= f.label 'name' %><br>
    	  <%= f.text_field :name %>
      </p>
      <p>
    	  <%= f.label 'surname' %><br>
    	  <%= f.text_field :surname %>
      </p>

      <p>
        <%= f.label 'ISBN' %><br>
        <%= f.text_field :isbn %>
      </p>

      <p>
        <%= f.label 'color' %><br>
        <%= f.text_field :color %>
      </p>
      
      <p>
        <%= f.label 'category' %><br>
        <%= f.text_field :category %>
      </p>
      <p>
        <%= f.label 'tags' %><br>
        <%= f.text_field :tags %>
      </p>
      <p>
        <%= f.label 'lease' %><br>
        <%= f.text_field :lease %>
      </p>
      <p>
        <%= f.label 'cover' %><br>
        <%= f.text_field :cover %>
      </p>
      

      <p>
          <%= f.submit %>
       </p>


    	<% end %>

app/views/books/edit.html.erb
<div id="page_wrapper">
   
    <h1>Edit book</h1>

    <%= render 'form' %>

  </div>

app/views/books/index.html.erb
<% @books.each do |book| %>
	<div class="book_wrapper">
      <h2 class="title"><%= link_to book.title, book %></h2>
      <h3><%=h book.subtitle %></h3>
	  <p><%= book.name %> <%= book.surname %></p>
	  <p>ISBN <%= book.isbn %></p>
	  <p><%= book.category %></p>
	  <p><%= book.color %></p>
	  <p><%= book.tags %></p>
	  <p><%= book.lease %></p>
	  <p><%= book.cover %></p>  
	</div>
 <% end %>

<div class="book_wrapper"> 
    <%= will_paginate @book %>
</div>   

app/views/books/new.html.erb
<div id="page_wrapper">
   
    <h1>New book</h1>

    <%= form_for :book, url: books_path do |f| %>
      
      <!-- powiadomienie flash -->
      <% if @book.errors.any? %>
        <div id="errors">
          <h2><%= pluralize(@book.errors.count, "error") %> prevented this book from saving</h2>
            <ul>
              <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
      <% end %>

      <p>
    	  <%= f.label 'title' %><br>
    	  <%= f.text_field :title %>
      </p>
      <p>
    	  <%= f.label 'subtitle' %><br>
    	  <%= f.text_field :subtitle %>
      </p>
      <p>
    	  <%= f.label 'name' %><br>
    	  <%= f.text_field :name %>
      </p>
      <p>
    	  <%= f.label 'surname' %><br>
    	  <%= f.text_field :surname %>
      </p>
      <p>
          <%= f.submit %>
       </p>


    	<% end %>
  </div>

app/views/books/show.html.erb
<div id="book_content">

	<h1 class="title">
		<%= @book.title %>
	</h1>

	  <h2><%= @book.subtitle %></h2>
		  <p><%= @book.name %> <%= @book.surname %></p>
		  <p>ISBN <%= @book.isbn %></p>
		  <p><%= @book.category %></p>
		  <p><%= @book.color %></p>
		  <p><%= @book.tags %></p>
		  <p><%= @book.lease %></p>
		  <p><%= @book.cover %></p>
		  <br>

 <% if user_signed_in? %>
   <p> 
   	<%= link_to 'Edit', edit_book_path(@book) %> | 
    <%= link_to 'Delete', book_path(@book), method: :delete, data: { confirm: 'Are you sure?' } %>
   </p>
 <% end %>

</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshelf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=PT+Sans:400,700&subset=latin,latin-ext' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>
	  <div id="sidebar">
		<div id="logo">
		      <%= link_to root_path do %>
		      Bookshelf
		      <% end %>
		</div>
		   
		     <ul>
			     <li class="category">Links</li>
			     <li><%= link_to "about", about_path %></li>
		     </ul>

		     <% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Admin login", new_user_session_path %></p>
			<% end %>	
	  </div>
	  


	<div id="main_content">
	    <div id="header">

          <% if current_page?(root_path) %>
      	      <p>All books (<%= Book.count %>)</p>
          <% elsif current_page?(about_path) %>
              <p>About</p>
          <% else %>
              <%= link_to "Back to all books", root_path %>
          <% end %>	


    <!-- zastrzeżenie, że tylko pokaże się zalogowanemu użytkownikowi -->
          <% if user_signed_in? %>

		        <div class="buttons">
		          <button class="button"><%= link_to "New Book", new_book_path %></button>
		          <button class="button"><%= link_to "Log out", destroy_user_session_path, :method=>'delete' %></button>
		        </div>
          <% end %>    
	    </div>
        
        
	        <% flash.each do |name, msg| %>
			  <div class="book_wrapper">
				<%= content_tag(:div, msg, class: "alert") %>
			  </div>
			<% end %>
       
      <%= yield %>

    </div>

</body>
</html>

app/views/pages/about.html.erb
<div class="book_wrapper">
  <h1>About</h1>

    <div id="content">
      <p>A little bookshelf...</p>
    </div>

</div>